name: Docker Releases

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        id: get_version
        run: |
          echo ::set-output name=VERSION1::${GITHUB_REF#refs/*/}
          echo ::set-output name=VERSION2::${GITHUB_REF#refs/*/v}
        shell: bash

      - name: Version
        run: |
          echo Version1: $VERSION1
          echo Version2: $VERSION2
        shell: bash

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: -7
          format: 'MM-DD-YYYY'

      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ssh-key: ${{ secrets.ACTIONSKEY }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push latest DNDGenerator
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: orcpub/dndgenerator:latest

      - name: Build and push ${{ steps.get_version.outputs.VERSION2 }} DNDGenerator
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: orcpub/dndgenerator:release-${{ steps.get_version.outputs.VERSION2 }}